const { contextBridge, ipcRenderer, webUtils } = require('electron');

contextBridge.exposeInMainWorld('electronAPI', {
  downloadVideo: (data) => ipcRenderer.send('download-video', data),
  downloadAudio: (data) => ipcRenderer.send('download-audio', data),
  downloadInstagram: (data) => ipcRenderer.send('download-instagram', data),
  continueAnyway: () => ipcRenderer.send('continue-anyway'),
  downloadSubtitles: (data) => ipcRenderer.send('download-subtitles', data),
  openFolder: (filePath) => ipcRenderer.send('open-folder', filePath),
  openDownloadFolder: (type) => ipcRenderer.send('open-download-folder', type),
  onDownloadStatus: (callback) => ipcRenderer.on('download-status', (_event, value) => callback(value)),
  onDownloadProgress: (callback) => ipcRenderer.on('download-progress', (_event, value) => callback(value)),
  onDownloadComplete: (callback) => ipcRenderer.on('download-complete', (_event, value) => callback(value)),
  onDownloadError: (callback) => ipcRenderer.on('download-error', (_event, value) => callback(value)),
  onUpdateLog: (callback) => ipcRenderer.on('update-log', (_event, value) => callback(value)),
  onDependencyStatus: (callback) => ipcRenderer.on('dependency-status', (_event, value) => callback(value)),
  getSettings: () => ipcRenderer.invoke('get-settings'),
  saveSettings: (settings) => ipcRenderer.invoke('save-settings', settings),
  selectFolder: () => ipcRenderer.invoke('select-folder'),
  fetchVideoInfo: (url) => ipcRenderer.invoke('fetch-video-info', url),
  downloadClip: (data) => ipcRenderer.send('download-clip', data),
  getSystemInfo: () => ipcRenderer.invoke('get-system-info'),
  finishOnboarding: (data) => ipcRenderer.invoke('finish-onboarding', data),
  selectVideoFile: () => ipcRenderer.invoke('select-video-file'),
  getFileUrl: (filePath) => ipcRenderer.invoke('get-file-url', filePath),
  probeLocalVideo: (filePath) => ipcRenderer.invoke('probe-local-video', filePath),
  dividerImportUrl: (data) => ipcRenderer.send('divider-import-url', data),
  divideVideo: (data) => ipcRenderer.send('divide-video', data),
  onDivideStatus: (cb) => ipcRenderer.on('divide-status', (_event, value) => cb(value)),
  onDivideProgress: (cb) => ipcRenderer.on('divide-progress', (_event, value) => cb(value)),
  onDivideComplete: (cb) => ipcRenderer.on('divide-complete', (_event, value) => cb(value)),
  onDivideError: (cb) => ipcRenderer.on('divide-error', (_event, value) => cb(value)),
  onDividerImportComplete: (cb) => ipcRenderer.on('divider-import-complete', (_event, value) => cb(value)),
  getPathForFile: (file) => webUtils.getPathForFile(file),
});
