const { app, BrowserWindow, WebContentsView, ipcMain, shell, dialog, protocol, net, nativeImage, session, clipboard } = require('electron');
const path = require('path');
const { spawn, exec, spawnSync } = require('child_process');
const { pathToFileURL } = require('url');
const fs = require('fs');
const https = require('https');
const os = require('os');
const ctx = require('./ctx');

function isYtDlpSwitchInProgress(win, errorChannel = 'download-error') {
  if (ytDlpChannelSwitchInProgress) {
    if (win) {
      win.webContents.send(errorChannel, 'A yt-dlp update or channel switch is currently in progress. Please wait and try again.');
    }
    return true;
  }
  return false;
}

async function exportSessionCookies() {
  const cookieFile = path.join(app.getPath('userData'), 'app-cookies.txt');
  try {
    const cookies = await session.defaultSession.cookies.get({});
    let fileContent = '# Netscape HTTP Cookie File\n# This file is generated by YT-DLP GUI\n# Do not edit.\n\n';
    for (const cookie of cookies) {
      const domain = cookie.domain || '';
      const includeSubdomains = domain.startsWith('.') ? 'TRUE' : 'FALSE';
      const cookiePath = cookie.path || '/';
      const isSecure = cookie.secure ? 'TRUE' : 'FALSE';
      const expiration = cookie.expirationDate ? Math.round(cookie.expirationDate) : 0;
      const name = cookie.name || '';
      const value = cookie.value || '';
      
      fileContent += `${domain}\t${includeSubdomains}\t${cookiePath}\t${isSecure}\t${expiration}\t${name}\t${value}\n`;
    }
    fs.writeFileSync(cookieFile, fileContent, 'utf8');
    return cookieFile;
  } catch (err) {
    console.error('Failed to export app session cookies:', err);
    return null;
  }
}

async function appendYtDlpCookieArgs(args, cookieConfig) {
  if (cookieConfig === false) return args;

  let browser = '';
  let profile = '';
  let customCookiesFile = '';
  
  if (cookieConfig && typeof cookieConfig === 'object') {
    browser = cookieConfig.browser || '';
    profile = cookieConfig.profile || '';
    customCookiesFile = cookieConfig.cookiesFile || '';
  } else {
    browser = ctx.settings.cookiesFromBrowser || '';
    profile = ctx.settings.cookiesBrowserProfile || '';
    customCookiesFile = ctx.settings.cookiesFile || '';
  }

  if (!browser) return args;

  if (browser === 'file') {
    if (customCookiesFile && fs.existsSync(customCookiesFile)) {
      return ['--cookies', customCookiesFile, ...args];
    }
    return args;
  }

  if (browser === 'app-browser') {
    const exportedFile = await exportSessionCookies();
    if (exportedFile && fs.existsSync(exportedFile)) {
      return ['--cookies', exportedFile, ...args];
    }
    return args;
  }

  const normalizedProfile = profile.trim().replace(/^["']|["']$/g, '');
  const value = normalizedProfile ? `${browser}:${normalizedProfile}` : browser;
  return ['--cookies-from-browser', value, ...args];
}

const YT_DLP_CHANNELS = ['stable', 'nightly', 'master'];
const YT_DLP_CHANNEL_BASES = {
  stable: 'https://github.com/yt-dlp/yt-dlp/releases/latest/download',
  nightly: 'https://github.com/yt-dlp/yt-dlp-nightly-builds/releases/latest/download',
  master: 'https://github.com/yt-dlp/yt-dlp-master-builds/releases/latest/download'
};

let ytDlpChannelSwitchInProgress = false;

function normalizeYtDlpChannel(channel) {
  const normalized = String(channel || 'master').trim().toLowerCase();
  return YT_DLP_CHANNELS.includes(normalized) ? normalized : 'master';
}

function getYtDlpBinaryFileName() {
  if (process.platform === 'win32') return 'yt-dlp.exe';
  if (process.platform === 'darwin') return 'yt-dlp_macos';
  return 'yt-dlp';
}

function getYtDlpDownloadUrl(channel) {
  const normalized = normalizeYtDlpChannel(channel);
  const base = YT_DLP_CHANNEL_BASES[normalized];
  return `${base}/${getYtDlpBinaryFileName()}`;
}

function parseYtDlpChannelFromOutput(output) {
  const text = output || '';
  const match = text.match(/(?:updated yt-dlp to|latest version:|yt-dlp is up to date \()\s*(\w+)@/i);
  return match ? normalizeYtDlpChannel(match[1]) : '';
}

function normalizeInstagramUrl(url) {
  try {
    const parsed = new URL(url.trim());
    if (!parsed.hostname.includes('instagram.com') && parsed.hostname !== 'instagr.am') {
      return url.trim();
    }
    parsed.search = '';
    parsed.hash = '';
    if (!parsed.pathname.endsWith('/')) {
      parsed.pathname += '/';
    }
    return parsed.toString();
  } catch {
    return url.trim();
  }
}

function formatInstagramDownloadError(code, stderr, label) {
  let msg = `[INSTAGRAM ${label}] Download failed with code ${code}`;
  const combined = (stderr || '').toLowerCase();
  if (
    combined.includes('empty media response') ||
    combined.includes('login required') ||
    combined.includes('rate-limit')
  ) {
    if (!ctx.settings.cookiesFromBrowser) {
      msg += '. Instagram may require login cookies — open Settings and configure Browser Cookies (close the browser first).';
    } else {
      msg += '. Close your browser completely and retry, or verify the post opens when logged into Instagram.';
    }
    if (normalizeYtDlpChannel(ctx.settings.ytDlpChannel) !== 'master') {
      msg += ' For Instagram without cookies, switch yt-dlp to the Master channel in Settings.';
    }
  }
  return msg;
}

async function cleanupOldBinaries(dir) {
  try {
    if (!fs.existsSync(dir)) return;
    const entries = fs.readdirSync(dir);
    for (const file of entries) {
      if (file.includes('.old_') || file.endsWith('.tmp') || file.includes('.tmp_')) {
        const fullPath = path.join(dir, file);
        try {
          fs.unlinkSync(fullPath);
        } catch (e) {
          // File may still be locked by another process
        }
      }
    }
  } catch (e) {}
}

async function replaceLocalBinary(tempPath, destPath, { minSizeBytes = 500000, maxRetries = 6, retryDelayMs = 300 } = {}) {
  if (!fs.existsSync(tempPath)) {
    throw new Error(`Replacement failed: temporary binary not found at ${tempPath}`);
  }

  const stat = fs.statSync(tempPath);
  if (stat.size < minSizeBytes) {
    try { fs.unlinkSync(tempPath); } catch (e) {}
    throw new Error(`Downloaded binary appears incomplete or corrupted (${stat.size} bytes). Expected at least ${minSizeBytes} bytes.`);
  }

  const dir = path.dirname(destPath);
  if (!fs.existsSync(dir)) {
    fs.mkdirSync(dir, { recursive: true });
  }

  // If destination binary already exists, handle replacement safely
  let backupPath = null;
  if (fs.existsSync(destPath)) {
    backupPath = path.join(dir, `${path.basename(destPath)}.old_${Date.now()}_${Math.random().toString(36).slice(2, 6)}`);
    let replaced = false;
    let lastError = null;

    for (let attempt = 1; attempt <= maxRetries; attempt++) {
      try {
        fs.renameSync(destPath, backupPath);
        replaced = true;
        break;
      } catch (err) {
        lastError = err;
        if (err.code === 'EPERM' || err.code === 'EBUSY' || err.code === 'EACCES') {
          if (process.platform === 'win32' && attempt >= 2) {
            try {
              exec(`taskkill /F /IM ${path.basename(destPath)}`, { windowsHide: true }, () => {});
            } catch (kErr) {}
          }
          try {
            fs.unlinkSync(destPath);
            replaced = true;
            break;
          } catch (delErr) {
            lastError = delErr;
          }
        }
        if (attempt < maxRetries) {
          await ctx.sleep(retryDelayMs * attempt);
        }
      }
    }

    if (!replaced && fs.existsSync(destPath)) {
      try { fs.unlinkSync(tempPath); } catch (e) {}
      throw new Error(`Cannot replace binary: ${path.basename(destPath)} is currently locked or in use by a background process. (${lastError?.message || 'File locked'})`);
    }
  }

  try {
    fs.renameSync(tempPath, destPath);
  } catch (renameErr) {
    if (backupPath && fs.existsSync(backupPath) && !fs.existsSync(destPath)) {
      try {
        fs.renameSync(backupPath, destPath);
      } catch (restoreErr) {
        console.error('Failed to restore backup binary:', restoreErr);
      }
    }
    throw new Error(`Failed to place new binary into target destination: ${renameErr.message}`);
  }

  ctx.makeExecutable(destPath);

  if (backupPath && fs.existsSync(backupPath)) {
    try {
      fs.unlinkSync(backupPath);
    } catch (e) {}
  }

  cleanupOldBinaries(dir);
  return true;
}

async function getYtDlpVersionInfo() {
  const localExists = fs.existsSync(ctx.localYtDlp);
  if (!localExists && !(await ctx.isCommandInPath('yt-dlp'))) {
    return {
      available: false,
      version: '',
      channel: normalizeYtDlpChannel(ctx.settings.ytDlpChannel),
      installedChannel: '',
      local: false,
      path: ctx.getYtDlpPath()
    };
  }

  // To get the actual compiled channel/build and version, execute yt-dlp -v
  const versionResult = await runYtDlpProcess(['-v'], false, 10000);
  const combined = `${versionResult.stdout}\n${versionResult.stderr}`;
  
  let version = '';
  let installedChannel = '';

  // Format example: [debug] yt-dlp version master@2026.07.06.214832 from yt-dlp/yt-dlp-master-builds [b3854cc41] (win_exe)
  // or: [debug] yt-dlp version 2026.01.26 from yt-dlp/yt-dlp [b3854cc41]
  const debugMatch = combined.match(/\[debug\]\s+yt-dlp\s+version\s+(?:(\w+)@)?([^\s\[]+)/i);
  if (debugMatch) {
    if (debugMatch[1]) {
      installedChannel = normalizeYtDlpChannel(debugMatch[1]);
    }
    version = debugMatch[2].trim();
  }

  // If no channel parsed directly from version tag, inspect repo sources in debug lines
  if (!installedChannel) {
    if (/yt-dlp-master-builds/i.test(combined)) {
      installedChannel = 'master';
    } else if (/yt-dlp-nightly-builds/i.test(combined)) {
      installedChannel = 'nightly';
    } else if (/yt-dlp\/yt-dlp/i.test(combined) || /github\.com\/yt-dlp\/yt-dlp/i.test(combined)) {
      installedChannel = 'stable';
    }
  }

  // Fallback to basic version check if -v parsing didn't get version
  if (!version) {
    const fallbackResult = await runYtDlpProcess(['--version'], false, 5000);
    version = (fallbackResult.stdout || '').trim().split('\n')[0].trim();
  }

  // Fallback to saved settings if channel could not be identified from output
  if (!installedChannel) {
    installedChannel = ctx.settings.ytDlpInstalledChannel || ctx.settings.ytDlpChannel || 'master';
  }

  return {
    available: !!version,
    version,
    channel: normalizeYtDlpChannel(ctx.settings.ytDlpChannel),
    installedChannel: normalizeYtDlpChannel(installedChannel),
    local: localExists,
    path: ctx.getYtDlpPath()
  };
}

async function downloadYtDlpFromChannel(win, channel, { onProgress } = {}) {
  if (!fs.existsSync(ctx.localBinDir)) {
    fs.mkdirSync(ctx.localBinDir, { recursive: true });
  }

  const targetChannel = normalizeYtDlpChannel(channel);
  const tempPath = path.join(ctx.localBinDir, `yt-dlp.tmp_${Date.now()}`);

  const downloadUrl = getYtDlpDownloadUrl(targetChannel);
  await ctx.downloadFile(downloadUrl, tempPath, win, 'yt-dlp', onProgress);

  await replaceLocalBinary(tempPath, ctx.localYtDlp, { minSizeBytes: 1000000 });
  return targetChannel;
}

async function switchYtDlpChannel(win, channel, { silent = false, force = true } = {}) {
  const targetChannel = normalizeYtDlpChannel(channel);

  if (force) {
    await ctx.stopAllBlockingTasks(win, `switching yt-dlp to ${targetChannel} channel`);
  }

  if (ytDlpChannelSwitchInProgress) {
    return {
      ok: false,
      level: 'warning',
      message: 'A yt-dlp build update or channel switch is already in progress.',
      channel: targetChannel
    };
  }

  ytDlpChannelSwitchInProgress = true;
  const log = (message) => {
    if (!silent && win && !win.isDestroyed()) {
      win.webContents.send('update-log', message);
    }
  };

  try {
    log(`[yt-dlp] Downloading clean ${targetChannel} release build...`);
    await downloadYtDlpFromChannel(win, targetChannel);

    const versionInfo = await getYtDlpVersionInfo();
    if (!versionInfo.available || !versionInfo.version) {
      throw new Error('yt-dlp binary verification failed after channel switch.');
    }

    ctx.saveSettingsInternal({
      ytDlpChannel: targetChannel,
      ytDlpInstalledChannel: versionInfo.installedChannel || targetChannel,
      ytDlpInstalledVersion: versionInfo.version
    });

    const message = `yt-dlp is now on the ${versionInfo.installedChannel} channel (${versionInfo.version}).`;
    log(`[yt-dlp] ${message}`);
    if (win && !win.isDestroyed()) {
      win.webContents.send('yt-dlp-channel-changed', {
        ok: true,
        channel: versionInfo.installedChannel,
        targetChannel,
        version: versionInfo.version,
        source: 'switch'
      });
    }

    return {
      ok: true,
      level: 'success',
      message,
      channel: versionInfo.installedChannel,
      targetChannel,
      version: versionInfo.version
    };
  } catch (err) {
    console.error('Failed to switch yt-dlp channel:', err);
    const message = `Failed to switch yt-dlp to ${targetChannel}: ${err.message}`;
    log(`[yt-dlp] ${message}`);
    if (win && !win.isDestroyed()) {
      win.webContents.send('yt-dlp-channel-changed', {
        ok: false,
        error: message,
        targetChannel
      });
    }
    return {
      ok: false,
      level: 'error',
      message,
      tip: err.message.includes('locked') ? err.message : 'Please check your internet connection and try again.',
      channel: targetChannel
    };
  } finally {
    ytDlpChannelSwitchInProgress = false;
  }
}

async function forceUpdateYtDlp(win, channel, { silent = false, force = true } = {}) {
  const targetChannel = normalizeYtDlpChannel(channel || ctx.settings.ytDlpChannel);

  if (force) {
    await ctx.stopAllBlockingTasks(win, `force updating yt-dlp on ${targetChannel} channel`);
  }

  if (ytDlpChannelSwitchInProgress) {
    return {
      ok: false,
      level: 'warning',
      message: 'A yt-dlp update or channel switch is already in progress.',
      channel: targetChannel
    };
  }

  ytDlpChannelSwitchInProgress = true;
  const log = (message) => {
    if (!silent && win && !win.isDestroyed()) {
      win.webContents.send('update-log', message);
    }
  };

  try {
    log(`[yt-dlp] Forcefully downloading latest release build for ${targetChannel} channel...`);
    await downloadYtDlpFromChannel(win, targetChannel);

    const versionInfo = await getYtDlpVersionInfo();
    if (!versionInfo.available || !versionInfo.version) {
      throw new Error('yt-dlp binary verification failed after force update.');
    }

    ctx.saveSettingsInternal({
      ytDlpChannel: targetChannel,
      ytDlpInstalledChannel: versionInfo.installedChannel || targetChannel,
      ytDlpInstalledVersion: versionInfo.version
    });

    const message = `yt-dlp forcefully updated to latest ${versionInfo.installedChannel} build (${versionInfo.version}).`;
    log(`[yt-dlp] ${message}`);
    if (win && !win.isDestroyed()) {
      win.webContents.send('yt-dlp-channel-changed', {
        ok: true,
        channel: versionInfo.installedChannel,
        targetChannel,
        version: versionInfo.version,
        source: 'force-update'
      });
    }

    return {
      ok: true,
      level: 'success',
      message,
      channel: versionInfo.installedChannel,
      targetChannel,
      version: versionInfo.version
    };
  } catch (err) {
    console.error('Failed to force update yt-dlp:', err);
    const message = `Failed to force update yt-dlp (${targetChannel}): ${err.message}`;
    log(`[yt-dlp] ${message}`);
    if (win && !win.isDestroyed()) {
      win.webContents.send('yt-dlp-channel-changed', {
        ok: false,
        error: message,
        targetChannel
      });
    }
    return {
      ok: false,
      level: 'error',
      message,
      tip: err.message.includes('locked') ? err.message : 'Please check your internet connection and try again.',
      channel: targetChannel
    };
  } finally {
    ytDlpChannelSwitchInProgress = false;
  }
}

async function syncYtDlpChannel(win, { ensureLocal = false, silent = false } = {}) {
  const targetChannel = normalizeYtDlpChannel(ctx.settings.ytDlpChannel);
  const exists = fs.existsSync(ctx.localYtDlp);

  if (ensureLocal && !exists) {
    return switchYtDlpChannel(win, targetChannel, { silent });
  }

  if (!exists) {
    return false;
  }

  const actualInfo = await getYtDlpVersionInfo();
  if (!actualInfo.available) {
    return switchYtDlpChannel(win, targetChannel, { silent });
  }

  ctx.saveSettingsInternal({
    ytDlpInstalledChannel: actualInfo.installedChannel,
    ytDlpInstalledVersion: actualInfo.version
  });

  if (actualInfo.installedChannel !== targetChannel) {
    return switchYtDlpChannel(win, targetChannel, { silent });
  }

  return false;
}

async function runYtDlpProcess(args, cookieConfig, timeoutMs = 90000) {
  const cookieArgs = await appendYtDlpCookieArgs(args, cookieConfig);
  return new Promise((resolve) => {
    const proc = spawn(ctx.getYtDlpPath(), cookieArgs, {
      windowsHide: true
    });
    ctx.registerYtDlpProcess(proc);
    let stdout = '';
    let stderr = '';
    let settled = false;

    const finish = (result) => {
      if (settled) return;
      settled = true;
      clearTimeout(timer);
      resolve(result);
    };

    const timer = setTimeout(() => {
      try { proc.kill(); } catch { /* ignore */ }
      finish({
        code: -2,
        stdout,
        stderr: `${stderr}\nTimed out after ${Math.round(timeoutMs / 1000)}s. Close the browser and try again.`.trim(),
        timedOut: true
      });
    }, timeoutMs);

    proc.stdout.on('data', (d) => { stdout += d.toString(); });
    proc.stderr.on('data', (d) => { stderr += d.toString(); });
    proc.on('close', (code) => finish({ code, stdout, stderr, timedOut: false }));
    proc.on('error', (err) => finish({
      code: -1,
      stdout,
      stderr: err.code === 'ENOENT'
        ? `yt-dlp was not found. Install it or let the app download it from Settings > dependencies.\n${err.message}`
        : err.message,
      timedOut: false
    }));
  });
}

function hasCookieExtractionFailure(output) {
  const lower = (output || '').toLowerCase();
  return (
    (lower.includes('could not copy') && lower.includes('cookie')) ||
    lower.includes('error extracting cookies') ||
    lower.includes('failed to extract cookies') ||
    lower.includes('unsupported browser') ||
    lower.includes('no such browser')
  );
}

function parseYtDlpCookieError(stderr, timedOut = false) {
  if (timedOut) {
    return {
      message: 'Cookie test timed out.',
      tip: 'Close the selected browser completely, then run the test again.'
    };
  }

  const text = (stderr || '').trim();
  const lower = text.toLowerCase();

  if (lower.includes('yt-dlp was not found') || lower.includes('enoent')) {
    return {
      message: 'yt-dlp is not available on this system.',
      tip: 'Open the app setup wizard or install yt-dlp, then try again.'
    };
  }
  if (lower.includes('could not copy') && lower.includes('cookie')) {
    return {
      message: 'Could not read the browser cookie database.',
      tip: 'Close the selected browser completely (all windows), then run the test again. Chromium browsers lock their cookie file while open.'
    };
  }
  if (lower.includes('failed to decrypt') || lower.includes('keyring')) {
    return {
      message: 'Cookies were found but could not be decrypted.',
      tip: 'On Linux, you may need a keyring option. On Windows, close the browser and retry.'
    };
  }
  if (lower.includes('unsupported browser') || lower.includes('no such browser')) {
    return {
      message: 'That browser is not supported or could not be located.',
      tip: 'Pick the browser you actually use and make sure it is installed.'
    };
  }
  if (lower.includes('profile') && (lower.includes('not found') || lower.includes('does not exist'))) {
    return {
      message: 'The browser profile name could not be found.',
      tip: 'Check the exact profile name in your browser settings, or leave the profile blank for default.'
    };
  }

  const lines = text.split('\n').map((l) => l.trim()).filter(Boolean);
  const errorLines = lines.filter((l) => /error/i.test(l));
  return {
    message: errorLines[errorLines.length - 1] || lines[lines.length - 1] || 'Cookie test failed.',
    tip: 'Close the browser, confirm the profile name, and try again.'
  };
}

function cleanYtDlpError(stderr) {
  const lines = (stderr || '').split('\n').map((l) => l.trim()).filter(Boolean);
  const errorLines = lines.filter((l) => /error/i.test(l));
  return errorLines.join(' ') || lines.slice(-2).join(' ') || 'Unknown yt-dlp error.';
}

async function detectYoutubeLogin(cookieOverride) {
  const probeUrls = [
    'https://www.youtube.com/playlist?list=WL',
    'https://www.youtube.com/feed/subscriptions',
    'https://www.youtube.com/playlist?list=LL'
  ];

  for (const url of probeUrls) {
    const result = await runYtDlpProcess([
      '--flat-playlist',
      '--dump-single-json',
      '--playlist-items', '1',
      '--no-warnings',
      '--ignore-no-formats-error',
      url
    ], cookieOverride, 60000);

    if (result.code !== 0 || hasCookieExtractionFailure(`${result.stderr}\n${result.stdout}`)) {
      continue;
    }

    try {
      const parsed = JSON.parse(result.stdout);
      const title = (parsed.title || '').toLowerCase();
      if (title.includes('sign in') || title.includes('login required')) {
        continue;
      }
      if (
        parsed._type === 'playlist' ||
        parsed.id === 'WL' ||
        parsed.id === 'LL'
      ) {
        return { loggedIn: true, label: parsed.title || 'YouTube account feed' };
      }
    } catch {
      // try next probe
    }
  }

  return { loggedIn: false, label: '' };
}

async function testBrowserCookiesInternal({ browser, profile, cookiesFile, testUrl }) {
  if (!browser) {
    return {
      ok: false,
      level: 'error',
      message: 'Select a browser before testing cookies.',
      tip: 'Choose Chrome, Edge, Firefox, or another supported browser from the dropdown.'
    };
  }

  if (browser === 'file') {
    if (!cookiesFile) {
      return {
        ok: false,
        level: 'error',
        message: 'No cookies file selected.',
        tip: 'Please select a valid Netscape format cookies text file (.txt).'
      };
    }
    if (!fs.existsSync(cookiesFile)) {
      return {
        ok: false,
        level: 'error',
        message: 'The selected cookies file does not exist.',
        tip: 'Verify the file path and make sure the file is at that location.'
      };
    }
  }

  if (browser === 'app-browser') {
    const cookies = await session.defaultSession.cookies.get({});
    if (cookies.length === 0) {
      return {
        ok: false,
        level: 'warning',
        message: 'No cookies found in the In-App Browser.',
        tip: 'Open the "Browser" tab, search/go to YouTube or Instagram, and log in to your account. Then run this test again.'
      };
    }
  }

  const versionCheck = await runYtDlpProcess(['--version'], false, 15000);
  if (versionCheck.code !== 0) {
    return {
      ok: false,
      level: 'error',
      message: 'yt-dlp is not available.',
      tip: cleanYtDlpError(versionCheck.stderr) || 'Install yt-dlp or complete the app dependency setup first.'
    };
  }

  const cookieOverride = {
    browser,
    profile: (profile || '').trim().replace(/^["']|["']$/g, ''),
    cookiesFile
  };

  const extractionTest = await runYtDlpProcess([
    '--simulate',
    '--no-warnings',
    '--ignore-no-formats-error',
    '--print', '%(title)s',
    'https://www.youtube.com/watch?v=jNQXAC9IVRw'
  ], cookieOverride, 60000);

  const extractionOutput = `${extractionTest.stderr}\n${extractionTest.stdout}`;

  if (
    extractionTest.code !== 0 ||
    extractionTest.code === -1 ||
    extractionTest.timedOut ||
    hasCookieExtractionFailure(extractionOutput)
  ) {
    const parsed = parseYtDlpCookieError(extractionOutput, extractionTest.timedOut);
    return {
      ok: false,
      level: 'error',
      message: parsed.message,
      tip: parsed.tip,
      extractionOk: false,
      youtubeLoggedIn: false
    };
  }

  const loginProbe = await detectYoutubeLogin(cookieOverride);
  const youtubeLoggedIn = loginProbe.loggedIn;

  if (testUrl && testUrl.trim()) {
    const urlTest = await runYtDlpProcess([
      '--simulate',
      '--no-warnings',
      '--ignore-no-formats-error',
      '--print', '%(title)s',
      testUrl.trim()
    ], cookieOverride, 90000);

    const urlOutput = `${urlTest.stderr}\n${urlTest.stdout}`;

    if (urlTest.code !== 0 || urlTest.timedOut || hasCookieExtractionFailure(urlOutput)) {
      return {
        ok: false,
        level: 'error',
        message: urlTest.timedOut
          ? 'Cookie test timed out while checking your URL.'
          : 'Cookies load, but your test URL could not be accessed.',
        detail: cleanYtDlpError(urlOutput),
        tip: urlTest.timedOut
          ? 'Close the browser and try again with a shorter or public test clip first.'
          : 'Make sure you are signed in to that site in the selected browser profile.',
        extractionOk: true,
        youtubeLoggedIn
      };
    }

    const title = urlTest.stdout.trim();
    return {
      ok: true,
      level: 'success',
      message: 'Cookies verified — your test URL is accessible.',
      detail: title ? `Reached: ${title}` : 'yt-dlp can access the URL with these cookies.',
      extractionOk: true,
      youtubeLoggedIn
    };
  }

  if (youtubeLoggedIn) {
    return {
      ok: true,
      level: 'success',
      message: 'Cookies working — YouTube account detected in this browser profile.',
      detail: loginProbe.label
        ? `Verified via: ${loginProbe.label}`
        : 'yt-dlp can read cookies and sees an active YouTube session.',
      extractionOk: true,
      youtubeLoggedIn: true
    };
  }

  return {
    ok: true,
    level: 'warning',
    message: 'Cookie extraction works, but no YouTube login was detected.',
    detail: 'Sign in to YouTube in that browser profile, then test again. For private non-YouTube sites, use the optional test URL below.',
    extractionOk: true,
    youtubeLoggedIn: false
  };
}

async function checkUpdates(win, retryCount = 0) {
  const targetChannel = normalizeYtDlpChannel(ctx.settings.ytDlpChannel);

  if (ctx.activeYtDlpProcesses.size > 0 || ytDlpChannelSwitchInProgress) {
    const activeCommands = Array.from(ctx.activeYtDlpProcesses).map(p => {
      const args = p.spawnargs ? p.spawnargs.slice(1).join(' ') : '';
      return `${path.basename(p.spawnfile || 'yt-dlp')} ${args}`;
    });
    const reason = ytDlpChannelSwitchInProgress 
      ? 'channel switch in progress' 
      : `active tasks: ${activeCommands.join(', ')}`;

    if (retryCount < 3) {
      if (win && !win.isDestroyed()) {
        win.webContents.send('update-log', `[yt-dlp update] Update check postponed (${reason}). Retrying in 5 seconds...`);
      }
      setTimeout(() => {
        checkUpdates(win, retryCount + 1);
      }, 5000);
    } else {
      if (win && !win.isDestroyed()) {
        win.webContents.send('update-log', `[yt-dlp update] Update check postponed: yt-dlp is currently busy (${reason}).`);
      }
    }
    return;
  }

  if (win && !win.isDestroyed()) {
    win.webContents.send('update-log', `[yt-dlp update] Checking for updates on the ${targetChannel} channel...`);
  }

  try {
    // 1. Try yt-dlp built-in update check first without passing browser cookies
    const updateResult = await runYtDlpProcess(['--update-to', targetChannel], false, 35000);
    const combined = `${updateResult.stdout}\n${updateResult.stderr}`;

    const updateSucceeded = updateResult.code === 0 ||
      /updated yt-dlp to/i.test(combined) ||
      /is up to date/i.test(combined);

    if (updateSucceeded) {
      if (win && !win.isDestroyed()) {
        win.webContents.send('update-log', '[yt-dlp update] Update check completed successfully.');
      }
      const info = await getYtDlpVersionInfo();
      if (info.available) {
        ctx.saveSettingsInternal({
          ytDlpInstalledChannel: info.installedChannel,
          ytDlpInstalledVersion: info.version
        });
        if (win && !win.isDestroyed()) {
          win.webContents.send('yt-dlp-channel-changed', {
            channel: info.installedChannel,
            targetChannel,
            version: info.version
          });
        }
      }
    } else {
      // 2. Built-in --update-to failed (common on Windows with file locks or GitHub API limitations).
      // Fall back to direct binary download from official GitHub release assets.
      if (win && !win.isDestroyed()) {
        const errorSummary = cleanYtDlpError(combined) || `exit code ${updateResult.code}`;
        win.webContents.send('update-log', `[yt-dlp update] Built-in update check encountered: ${errorSummary}. Downloading latest ${targetChannel} build directly from GitHub Releases...`);
      }

      await downloadYtDlpFromChannel(win, targetChannel);
      const info = await getYtDlpVersionInfo();
      if (info.available && info.version) {
        ctx.saveSettingsInternal({
          ytDlpInstalledChannel: info.installedChannel || targetChannel,
          ytDlpInstalledVersion: info.version
        });
        if (win && !win.isDestroyed()) {
          win.webContents.send('update-log', `[yt-dlp update] Auto-update completed successfully: yt-dlp updated to latest ${info.installedChannel || targetChannel} build (${info.version}).`);
          win.webContents.send('yt-dlp-channel-changed', {
            channel: info.installedChannel || targetChannel,
            targetChannel,
            version: info.version
          });
        }
      } else {
        throw new Error('Downloaded binary could not be verified.');
      }
    }
  } catch (err) {
    console.error('Auto update check failed:', err);
    if (win && !win.isDestroyed()) {
      win.webContents.send('update-log', `[yt-dlp update] Auto-update check failed: ${err.message}`);
    }
  }

  // Verify FFmpeg is available
  const ffmpegPath = ctx.getFfmpegPath();
  const ffmpegCheck = spawn(ffmpegPath, ['-version']);
  ffmpegCheck.stdout.once('data', (data) => {
    const versionLine = data.toString().split('\n')[0];
    if (win && !win.isDestroyed()) {
      win.webContents.send('update-log', `[ffmpeg check] ${versionLine}`);
    }
  });
  ffmpegCheck.on('error', () => {
    if (win && !win.isDestroyed()) {
      win.webContents.send('update-log', `[ffmpeg error] ffmpeg not found in PATH! Audio extraction and video merging may fail.`);
    }
  });
}

ipcMain.handle('get-yt-dlp-info', async () => {
  return getYtDlpVersionInfo();
});

ipcMain.handle('switch-yt-dlp-channel', async (event, channel) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  const targetChannel = normalizeYtDlpChannel(channel || ctx.settings.ytDlpChannel);
  ctx.saveSettingsInternal({ ytDlpChannel: targetChannel });
  return switchYtDlpChannel(win, targetChannel);
});

ipcMain.handle('force-update-yt-dlp', async (event, channel) => {
  const win = BrowserWindow.fromWebContents(event.sender);
  const targetChannel = normalizeYtDlpChannel(channel || ctx.settings.ytDlpChannel);
  return forceUpdateYtDlp(win, targetChannel);
});

ipcMain.handle('test-browser-cookies', async (_event, payload) => {
  if (ytDlpChannelSwitchInProgress) {
    return {
      ok: false,
      level: 'warning',
      message: 'A yt-dlp update or channel switch is currently in progress.',
      tip: 'Please wait for the channel switch to complete.'
    };
  }

  try {
    return await testBrowserCookiesInternal(payload || {});
  } catch (err) {
    console.error('Cookie test failed:', err);
    return {
      ok: false,
      level: 'error',
      message: 'Cookie test could not be completed.',
      tip: err.message || 'Try again after closing the selected browser.'
    };
  }
});

ctx.isYtDlpSwitchInProgress = isYtDlpSwitchInProgress;
ctx.exportSessionCookies = exportSessionCookies;
ctx.appendYtDlpCookieArgs = appendYtDlpCookieArgs;
ctx.YT_DLP_CHANNELS = YT_DLP_CHANNELS;
ctx.YT_DLP_CHANNEL_BASES = YT_DLP_CHANNEL_BASES;
Object.defineProperty(ctx, 'ytDlpChannelSwitchInProgress', {
  get() { return ytDlpChannelSwitchInProgress; },
  set(v) { ytDlpChannelSwitchInProgress = v; },
  enumerable: true,
  configurable: true
});
ctx.normalizeYtDlpChannel = normalizeYtDlpChannel;
ctx.getYtDlpBinaryFileName = getYtDlpBinaryFileName;
ctx.getYtDlpDownloadUrl = getYtDlpDownloadUrl;
ctx.parseYtDlpChannelFromOutput = parseYtDlpChannelFromOutput;
ctx.normalizeInstagramUrl = normalizeInstagramUrl;
ctx.formatInstagramDownloadError = formatInstagramDownloadError;
ctx.cleanupOldBinaries = cleanupOldBinaries;
ctx.replaceLocalBinary = replaceLocalBinary;
ctx.getYtDlpVersionInfo = getYtDlpVersionInfo;
ctx.downloadYtDlpFromChannel = downloadYtDlpFromChannel;
ctx.switchYtDlpChannel = switchYtDlpChannel;
ctx.forceUpdateYtDlp = forceUpdateYtDlp;
ctx.syncYtDlpChannel = syncYtDlpChannel;
ctx.runYtDlpProcess = runYtDlpProcess;
ctx.hasCookieExtractionFailure = hasCookieExtractionFailure;
ctx.parseYtDlpCookieError = parseYtDlpCookieError;
ctx.cleanYtDlpError = cleanYtDlpError;
ctx.detectYoutubeLogin = detectYoutubeLogin;
ctx.testBrowserCookiesInternal = testBrowserCookiesInternal;
ctx.checkUpdates = checkUpdates;
module.exports = { isYtDlpSwitchInProgress, exportSessionCookies, appendYtDlpCookieArgs, YT_DLP_CHANNELS, YT_DLP_CHANNEL_BASES, ytDlpChannelSwitchInProgress, normalizeYtDlpChannel, getYtDlpBinaryFileName, getYtDlpDownloadUrl, parseYtDlpChannelFromOutput, normalizeInstagramUrl, formatInstagramDownloadError, cleanupOldBinaries, replaceLocalBinary, getYtDlpVersionInfo, downloadYtDlpFromChannel, switchYtDlpChannel, forceUpdateYtDlp, syncYtDlpChannel, runYtDlpProcess, hasCookieExtractionFailure, parseYtDlpCookieError, cleanYtDlpError, detectYoutubeLogin, testBrowserCookiesInternal, checkUpdates };
